name: "GitHub Metrics"

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  github-metrics:
    name: Profile
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Metrics embed
      uses: lowlighter/metrics@v3.28
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
